DROP TABLE ESTUDIANTE;
DROP TABLE INSTRUCTOR;
DROP TABLE CONSEJERO;

CREATE TABLE ESTUDIANTE (
    CODIGO NUMBER(8,0),
    NOMBRE VARCHAR2(100),
    APELLIDO VARCHAR2(100),
    EMAIL VARCHAR2(30),
    PRIMARY KEY (CODIGO)
);


INSERT INTO ESTUDIANTE VALUES (1, 'PEDRO', 'PEREZ', 'perez@javeriana.edu.co');
INSERT INTO ESTUDIANTE VALUES (10, 'MARIA', 'PEREZ', 'mariaperez@javeriana.edu.co');
INSERT INTO ESTUDIANTE VALUES (11, 'MARTA', 'PEREZ', 'martaperez@javeriana.edu.co');
INSERT INTO ESTUDIANTE VALUES (10, 'JUAN', 'PEREZ', 'juanperez@javeriana.edu.co');

COMMIT; /* Sirve para guardar los datos ingresados, si no lo hago hace rollback */

SELECT * FROM ESTUDIANTE;

-----------------------
CREATE TABLE INSTRUCTOR(
    CODIGO NUMBER (8,0),
    NOMBRES VARCHAR2 (50),
    APELLIDOS VARCHAR2 (50),
    SUELDO NUMBER (10,2),
    PRIMARY KEY (CODIGO)
);

-- Tiene llaver foranea que referencia a instructor en codigoinstructor
CREATE TABLE CONSEJERO(
    CODIGOESTUDIANTE NUMBER(8,0),
    CODIGOINSTRUCTOR NUMBER(8,0),
    FOREIGN KEY (CODIGOINSTRUCTOR) REFERENCES INSTRUCTOR(CODIGO), --ES OPCIONAL EN ORACLE, AUTOMATICAMENTE REFERENCIA A LA PRIMARY KEY
    FOREIGN KEY (CODIGOESTUDIANTE) REFERENCES ESTUDIANTE(CODIGO),
    PRIMARY KEY (CODIGOESTUDIANTE, CODIGOINSTRUCTOR)
);

-------------------------------------
-- PedrO perez tiene como consejero a david ospina de codigo 100
INSERT INTO INSTRUCTOR VALUES (100, 'DAVID', 'OSPINA', 7000000);
INSERT INTO CONSEJERO VALUES (1,100);
COMMIT;

SELECT * FROM CONSEJERO;